FROM python:3.9-slim

WORKDIR /todo-app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
COPY tests/ ./tests

ENV PYTHONPATH=/todo-app

CMD ["pytest", "tests/"]
